### PR TITLE
License project under the MIT license

### PR DESCRIPTION
**Pull request by nimble0**
~~This is same license Plover uses, so if you're happy for development to continue in the same vein as Plover, you need only merge this pull request.~~

I apologize for disturbing you about this again. Unfortunately, without an explicit license, no rights to use the code are given and open source development is not possible.

### CODE REVIEW

**Comment by Exaeta** [comment]
@nimble0 Apache and GPLv2 are incompatible licenses. So he can't really license it under GPLv2 because of that, as he includes Apache licensed code. I'd suggest licensing it under Apache or MIT or BSD or something instead. You could also use GPLv3 along the GPL route.

**Comment by nimble0** [comment]
In that case I suggest licensing under MIT. This has the most compatibility with other licenses.

I think the Apache licensed code could be removed and the option to relicense under GPLv2 would then be available.

**Comment by morinted** [comment]
+1 for this PR. Without a declared license, it's [technically not legal for anyone to fork the code](https://blog.codinghorror.com/pick-a-license-any-license/) and that would be a shame considering the wonderful work @brentn has done.

MIT is a good choice, but I'd almost lean towards GPLv3 (which *is Apache 2 compatible) because otherwise we will not be able to use Plover code within this codebase.

Either way, *any* license is better than no license.

**Comment by Exaeta** [comment]
@morinted MIT is 100% GPL compatible.

i.e. you can combine GPL and MIT code, in which case the terms of both apply. It's only combining GPLv2 and Apache that presents an issue (GPLv3 and Apache is not an issue, so if it is "GPLv2+" then you can combine the result under GPLv3 and Apache).

**Comment by brentn** [comment]
Thank you.

**Comment by nimble0** [comment]
Thanks!On 27 Jan 2018 22:42, Brent Nesbitt <notifications@github.com> wrote:Thank you.

**Pull request merged**
